- name: Deploy CloudWatch agent to EC2 via SSM
  hosts: ec2
  become: true
  vars:
    project: "aws-infra-platform"
    env: "dev"

  tasks:
    - name: Install CloudWatch agent
      ansible.builtin.dnf:
        name: amazon-cloudwatch-agent
        state: present

    - name: Deploy CloudWatch agent config
      ansible.builtin.template:
        src: templates/cloudwatch-agent.json.j2
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable CloudWatch agent
      ansible.builtin.shell: |
        /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
          -a fetch-config \
          -m ec2 \
          -s \
          -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
